apiVersion: v1
kind: ReplicationController
metadata:
  name: spring-boot-dubbo-producter
spec:
  template:
    metadata:
      labels:
        name: spring-boot-dubbo-producter
    spec:
      containers:
        - name: spring-boot-dubbo-producter
          image: registry.cn-shenzhen.aliyuncs.com/sjroom/alpine-java8
          volumeMounts:
            - name: workdir
              mountPath: "/export/App/"
      initContainers:
        - name: maven-install
          image: registry.cn-shenzhen.aliyuncs.com/sjroom/alpine-java8-maven3
          command: ["bash"]
          args: ["-c","/export/deploy.sh https://gitee.com/zw23534572/sjroom-demo.git master spring-boot/spring-boot-dubbo/spring-boot-dubbo-producter"]
          volumeMounts:
            - name: workdir
              mountPath: "/export/output/"
      volumes:
        - name: workdir
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-dubbo-producter
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30103
  selector:
        name: spring-boot-dubbo-producter
# https://gitee.com/zw23534572/sjroom-demo/raw/master/spring-boot/spring-boot-dubbo/spring-boot-dubbo-producter/k8s.yaml