apiVersion: v1
kind: ReplicationController
metadata:
  name: spring-boot-web
spec:
  template:
    metadata:
      labels:
        name: spring-boot-web
    spec:
      containers:
        - name: spring-boot-web
          image: registry.cn-shenzhen.aliyuncs.com/sjroom/alpine-java8
          volumeMounts:
            - name: workdir
              mountPath: "/export/App/"
      initContainers:
        - name: maven-install
          image: registry.cn-shenzhen.aliyuncs.com/sjroom/alpine-java8-maven3
          command: ["bash"]
          args: ["-c","/export/deploy.sh https://gitee.com/zw23534572/sjroom-demo.git master spring-boot/spring-boot-web"]
          volumeMounts:
            - name: workdir
              mountPath: "/export/output/"
      volumes:
        - name: workdir
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-web
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30101
  selector:
        name: spring-boot-web
# https://gitee.com/zw23534572/sjroom-demo/raw/master/spring-boot/spring-boot-web/k8s.yaml  